spring:
  rabbitmq:
    connection-timeout: 15000
    listener:
      # 表示消费者消费成功消息以后需要手工的进行签收(ack)，默认为auto
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
    password: guest
    username: guest
    virtual-host: /
    host: 127.0.0.1
    port: 5672